### ISSUE TITLE
cant get anything to display

### ISSUE THREAD

**Issue by alextheprotogoober** [NCPlyn/ProtogenHelmet-ESP32#2]
i have every thing downloaded and unziped but when i put an animation into the animater and click load it dosent do anything i am probably being dumb i am using MAX screens and right now they just display random dots :/ and dont respond to anything and on the index it dosent show what animation is being played and wont let me set any for tilt and when i click save it dosent it also doesn't let me change the animation it says file cant be accessed

**Comment by NCPlyn** [comment]
Do you have everything wired up correctly?
Did you use the code for the MAX displays?
Did you also upload the files into the LittleFS memory?
What output does the ESP give you into the console upon restart?

**Comment by NCPlyn** [comment]
You need to have Arduino IDE 1.x.x and install this plugin: https://github.com/lorol/arduino-esp32fs-plugin
There's how to install it and how to upload into the littlefs

**Comment by NCPlyn** [comment]
Use HUGE App (3MB No OTA/1MB SPIFFS) and do the ESP32 sketch data upload to LittleFS, the default animation should load and no error should be in the serial monitor at 115200 baudrate

**Comment by alextheprotogoober** [comment]
thank you so much it all seems to work and i hope this help other people but before i close this is there anyway i could add more matrix displays i get if that's difficult its just that my shnoot is too long and i would like to be able to make a bigger mouth and eyes and a extra nose but that's a lot and i get if that's possible sorry for the big ask

**Comment by NCPlyn** [comment]
yeah, there's planned release for an universial code which allows you to make any size/shape visor of max/ws2812 displays (beta branch)

**Comment by alextheprotogoober** [comment]
ah thank you so much man i really do apricate it :D
